### ISSUE TITLE
Problem running on HPC (works fine when run on command line!)

### ISSUE THREAD

**Issue by amootta** [AlexandrovLab/SigProfilerExtractor#103]
Hi there, I'm trying to run the SigProfilerExtractor on my HPC. 
This is the command I am running:

from SigProfilerExtractor import sigpro as sig
sig.sigProfilerExtractor("vcf", "vcf-output-files", 'vcf-files', minimum_signatures=1, reference_genome='GRCh38', opportunity_genome='GRCh38')

When I run this on normal python command line, it works perfectly and is able to process. However, I am trying to run it on my uni HPC, on slurm queue - using this command:

#!/bin/sh
#SBATCH --mem=40000
#SBATCH --job-name=sigprofiler
#SBATCH --nodes=1
#SBATCH --time=60:00:00
#SBATCH --partition=amd

module load conda
cd sigprofile

eval "$(conda shell.bash hook)"
conda activate sigprofile-3.6

python sigprofile.py

conda deactivate

It is giving me these errors: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/am3u20/.conda/envs/wgs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mainfs/cansci/Amatta_Mirandari/sigprofile/sigprofile.py", line 3, in <module>
    sig.sigProfilerExtractor("vcf", "/mainfs/cansci/Amatta_Mirandari/sigprofile/vcf-output-files", '/mainfs/cansci/Amatta_Mirandari/sigprofile/vcf-files', minimum_signatures=1, reference_genome='GRCh38',opportunity_genome='GRCh38')
  File "/home/am3u20/.local/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 611, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
  File "/home/am3u20/.local/lib/python3.7/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 305, in SigProfilerMatrixGeneratorFunc
    os.remove(error_file)
FileNotFoundError: [Errno 2] No such file or directory: '/mainfs/cansci/Amatta_Mirandari/sigprofile/vcf-files/logs/SigProfilerMatrixGenerator_vcf-files_GRCh382021-11-09.err'
IT's saying it is not finding the file, despite it existing in the exact path it is looking for. 

Any help with this would be very much appreciated please! Thanks

**Comment by mdbarnesUCSD** [comment]
Dear @amootta,

Could you please provide the JOB_METADATA.txt as well as sigprofile.py. You can provide the files here or to me via e-mail to mdbarnes@ucsd.edu.

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please re-open this issue if you are still experiencing the issue.

**Comment by Avramis** [comment]
Hi
I am experiencing the same problem. Did manage to solve this issue?


I have installed SigProfilerExtractor (following the instructions from https://osf.io/t6j7u/wiki/1.%20Installation/).
pip install SigProfilerExtractor

I try to test the toolwith the 21BRCA sample data.
When I run the SigProfilerExtractor on the command line it works ok.
The example code is 
python
from SigProfilerExtractor import sigpro as sig
sig.sigProfilerExtractor("vcf", "vcfExtractTest1", "/mnt/bmh01-rds/UoOxford_David_W/mqbssatj/Scripts/SigProfiler/SampleData/21BRCA/21BRCA_vcf/", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=4);


However, When I try to run the tool in HPC then I ghet the following error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/bmh01-rds/UoOxford_David_W/mqbssatj/Scripts/SigProfiler/Code/pythonScripts/SigProfilerExtcrTest1.py", line 5, in <module>
    sig.sigProfilerExtractor(sys.argv[1], sys.argv[2], sys.argv[3], reference_genome=sys.argv[4], minimum_signatures=int(sys.argv[5]), maximum_signatures=int(sys.argv[6]), cpu=int(sys.argv[7]));
  File "/mnt/fls01-home01/mqbssatj/.local/lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py", line 714, in sigProfilerExtractor
    processes = sub.decipher_signatures(execution_parameters,
  File "/mnt/fls01-home01/mqbssatj/.local/lib/python3.8/site-packages/SigProfilerExtractor/subroutines.py", line 540, in decipher_signatures
    results = parallel_runs(execution_parameters, genomes=genomes, totalProcesses=totalProcesses, \
  File "/mnt/fls01-home01/mqbssatj/.local/lib/python3.8/site-packages/SigProfilerExtractor/subroutines.py", line 446, in parallel_runs
    pool = multiprocessing.Pool(processes=n_cpu)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/apps/apps/binapps/anaconda3/2020.07/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
