### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerExtractor#107]
Hi, I want to decompose the De Novo Signatures form SignatureAnalyzer into COSMIC Signatures. Which run successfully for SBS96 and DBS78, but failed for ID83:

The context-83 decomposition plots pages were not able to be generated.
Traceback (most recent call last):
    decomp.decompose(signatures, activities, samples, indir, genome_build="GRCh38", refit_denovo_signatures=False, verbose=False)
  File "/share/apps/SigProfiler/lib/python3.9/site-packages/SigProfilerExtractor/decomposition.py", line 158, in decompose
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/share/apps/SigProfiler/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 939, in signature_decomposition
    _, exposures,L2dist,similarity, kldiv, correlation, cosine_similarity_with_four_signatures = ss.add_remove_signatures(sigDatabase,
  File "/share/apps/SigProfiler/lib/python3.9/site-packages/SigProfilerExtractor/single_sample.py", line 801, in add_remove_signatures
    add_exposures, add_distance, _ = add_signatures(W, M[:,np.newaxis], presentSignatures=copy.deepcopy(background_sigs), toBeAdded=loop_sig,
  File "/share/apps/SigProfiler4/lib/python3.9/site-packages/SigProfilerExtractor/single_sample.py", line 348, in add_signatures
    newExposure[idxmaxcoef] = round(newExposure[idxmaxcoef])+maxmutation-sum(newExposure)
ValueError: cannot convert float NaN to integer

**Comment by lalexandrov1018** [comment]
SigProfilerExtractor does not support decomposing signatures from SignatureAnalyzer.
