### ISSUE TITLE
Error on running in cluster

### ISSUE THREAD

**Issue by linkmonica** [AlexandrovLab/SigProfilerExtractor#129]
Hi,

I am trying to run SigProfiler on our slurm cluster and I am getting the following errors:
 I tried to look in closed issue posts but could not come up with a solution: I tired including the "if __name__ == '__main__':
    run()" from one post to my python script but it still gives the following error.

File "/home/uvi/be/mva/.local/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 541, in decipher_signatures
    verbose = False, replicate_generators=replicate_generators)
  File "/home/uvi/be/mva/.local/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 446, in parallel_runs
    pool = multiprocessing.Pool(processes=n_cpu)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/opt/cesga/easybuild-cesga/software/Compiler/gcccore/6.4.0/python/3.7.0/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by mdbarnesUCSD** [comment]
Hi @linkmonica,

Could you please include the script that you are running?

Thanks!

**Comment by linkmonica** [comment]
Hi,
I have included the script. and I call it in shell script for submission simply as:
python run_sigprofiler1.py samplename
[run_sigprofiler.py.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/8769057/run_sigprofiler.py.zip)

**Comment by mdbarnesUCSD** [comment]
Hi @linkmonica,

It sounds like you tried re-organizing your code, but try this script and if you still receive the error please reach out, thanks! 
[run_sigprofiler.py.zip](https://github.com/AlexandrovLab/SigProfilerExtractor/files/8781120/run_sigprofiler.py.zip)

**Comment by linkmonica** [comment]
Hi @mdbarnesUCSD ,

Thanks for your help, it works on my server now and thats very helpful,but there is a small issue that when I give argument "context=96" I get the following error, whereas with context as default, it runs completely and without any issues. (This is just for information,but does not stop my future work). Thanks once again for solving the issue.


Traceback (most recent call last):
  File "run_sigprofiler.py", line 12, in <module>
    run(input, output)
  File "run_sigprofiler.py", line 6, in run
    sig.sigProfilerExtractor("vcf",output, input, minimum_signatures=1, maximum_signatures=10, nmf_replicates=100, context_type="96",exome=1)
  File "/home/uvi/be/mva/.local/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 814, in sigProfilerExtractor
    decomp.spa_analyze( allgenomes, output, signatures=processAvg,genome_build="GRCh37", verbose=False,decompose_fit_option= True,denovo_refit_option=True,cosmic_fit_option=False,devopts=devopts)
  File "/home/uvi/be/mva/.local/lib/python3.7/site-packages/SigProfilerAssignment/decomposition.py", line 243, in spa_analyze
    refit_denovo_signatures=False)
  File "/home/uvi/be/mva/.local/lib/python3.7/site-packages/SigProfilerAssignment/decompose_sub_routines.py", line 488, in make_final_solution
    init_decomposed_sigs = union(init_decomposed_sigs, list(attribution[de_novo_sig]))
KeyError: '96A'

**Comment by rvangara** [comment]
Hi, 

This is an issue that is related to a variable in a dependent package of SigProfilerExtractor. Thanks for bringing this to our notice. We will fix it in the upcoming release.

Please reopen the ticket if the issue persists.
