### ISSUE TITLE
Key Error when running Sequenza segment input

### ISSUE THREAD

**Issue by Fractal10** [AlexandrovLab/SigProfilerExtractor#151]
Hi there,

I'm running into an issue when using Sequenza segment file input for CN-signature extraction. Upon issuing the following command...

sig.sigProfilerExtractor("seg:SEQUENZA", "results_cnv", "Test_segments.txt", reference_genome="mm10", minimum_signatures=1, nmf_replicates=100)

I get the following error:

************** Reported Current Memory Use: 1.04 GB *****************

Traceback (most recent call last):
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 575, in sigProfilerExtractor
    genomes = scna.generateCNVMatrix(cnv_file_type, input_data, cnv_file_type, output)
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/CNVMatrixGenerator.py", line 380, in generateCNVMatrix
    nmf_matrix, annotated_df = annotateSegFile(df, file_type, project, output_path)
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/SigProfilerMatrixGenerator/scripts/CNVMatrixGenerator.py", line 31, in annotateSegFile
    columns = list(df["sample"].unique())
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/xx/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'sample'

**Comment by azhark2** [comment]
Please make sure the first column of your segmentation file contains the sample name and is called 'sample'.

**Comment by marcos-diazg** [comment]
Thanks for your interest, @Fractal10! Please feel free to reopen the ticket if you are still experiencing issues.

Best,

Marcos
