### ISSUE TITLE
TypeError: _set_ticklabels() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by msubirana** [AlexandrovLab/SigProfilerExtractor#154]
Hi,

I got this error while using SigProfilerExtractor:

```
Time taken to collect 500 iterations for 1 signatures is 5064.01 seconds
Optimization time is 2.068568229675293 seconds
The reconstruction error is 0.0022, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msubirana/.local/lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py", line 915, in sigProfilerExtractor
    solution, all_stats = sub.stabVsRError(layer_directory+"/All_solutions_stat.csv", layer_directory, title, all_similirities_list, mtype=mutation_type, stability=stability, min_stability=min_stability, combined_stability=combined_stability)
  File "/home/msubirana/.local/lib/python3.8/site-packages/SigProfilerExtractor/subroutines.py", line 2306, in stabVsRError
    ax1.set_xticklabels(np.arange(min(t), max(t)+1, 1),list(), rotation=30)
  File "/home/msubirana/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 75, in wrapper
    return get_method(self)(*args, **kwargs)
TypeError: _set_ticklabels() takes 2 positional arguments but 3 were given

```

I used:
```
sig.sigProfilerExtractor("vcf", "results", vcf_path, minimum_signatures=1, maximum_signatures=3, reference_genome="GRCh38")

```

**Comment by mdbarnesUCSD** [comment]
Hi @msubirana,

It looks like there is an issue with the version of Matplotlib during plotting. Please use Matplolib version 3.4.3 to avoid this issue until further updates have been made.

Thanks!
