### ISSUE TITLE
CNV48 Matrix Input

### ISSUE THREAD

**Issue by mdbarnesUCSD** [AlexandrovLab/SigProfilerExtractor#167]
Code successfully runs with previous versions:
SigProfilerAssignment      0.0.11
SigProfilerExtractor       1.1.10

The code breaks with the following current versions:
SigProfilerAssignment      0.0.17
SigProfilerExtractor       1.1.15

Code to reproduce issue (input file attached below):
```
>>> from SigProfilerExtractor import sigpro as sig
>>> input="Battenberg_test.CNV48.matrix.txt"
>>> sig.sigProfilerExtractor("matrix", "cnv_output_spe", input, minimum_signatures=5, maximum_signatures=6, min_nmf_iterations=100, max_nmf_iterations=200, nmf_test_conv= 100, nmf_tolerance= 1e-8, nmf_replicates=2)
```

Error message:

>  Decomposing De Novo Signatures  .....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbarnes/anaconda3/envs/plotfast/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 855, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "/Users/mbarnes/anaconda3/envs/plotfast/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 352, in spa_analyze
    final_signatures = sub.signature_decomposition(processAvg, mutation_type, layer_directory2, genome_build=genome_build,cosmic_version=cosmic_version,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_plots, originalProcessAvg=originalProcessAvg,new_signature_thresh_hold=new_signature_thresh_hold,sig_exclusion_list=sig_exclusion_list,exome=exome, m_for_subgroups=m_for_subgroups)    
UnboundLocalError: local variable 'm_for_subgroups' referenced before assignment

[Battenberg_test.CNV48.matrix.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/9903636/Battenberg_test.CNV48.matrix.txt)

**Comment by mdbarnesUCSD** [comment]
This issue has been resolved with SigProfilerAssignment's v0.0.18 release.
