### ISSUE TITLE
 FileNotFoundError: SigProfilerAssignment/data/Reference_Signatures/GRCh38/COSMIC_v3.3_ID_GRCh38_exome.txt

### ISSUE THREAD

**Issue by JLiandbear** [AlexandrovLab/SigProfilerExtractor#183]
Hello,
I am trying latest version of SigProfilerAssignment (v0.0.21). It has no problem until it hits the last part of indel signatures.
Here's the error message:

Time taken to collect 100 iterations for 1 signatures is 106.56 seconds
Optimization time is 9.555011987686157 seconds
The reconstruction error is 0.535, average process stability is 1.0 and
the minimum process stability is 1.0 for 1 signatures

findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.

De Novo Fitting .....
|████████████████████████████████████████| 82/82 [100%] in 0.5s (150.34/s)

Decomposing De Novo Signatures .....
Generating plots for COSMIC_v3.3_ID_GRCh38_exome now...
Traceback (most recent call last):
File "", line 1, in
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 861, in sigProfilerExtractor
decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 497, in spa_analyze
final_signatures = sub.signature_decomposition(processAvg, mutation_type, layer_directory2, genome_build=genome_build,cosmic_version=cosmic_version,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg,new_signature_thresh_hold=new_signature_thresh_hold,sig_exclusion_list=sig_exclusion_list,exome=exome, m_for_subgroups=m_for_subgroups)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 402, in signature_decomposition
byte_plot = sp.run_PlotDecomposition(originalProcessAvg[denovo_cols],
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 503, in run_PlotDecomposition
basis_plots_dict = install_cosmic_plots(context_type=mtype,
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 120, in install_cosmic_plots
cosmic_buff_plots = sigPlt.plotID(cosmic_file_path, "buffer",
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 3934, in plotID
data=pd.read_csv(matrix_path,sep='\t',index_col=0)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
return func(*args, **kwargs)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
return func(*args, **kwargs)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
return _read(filepath_or_buffer, kwds)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in init
self._engine = self._make_engine(f, self.engine)
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
self.handles = get_handle(
File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/data/Reference_Signatures/GRCh38/COSMIC_v3.3_ID_GRCh38_exome.txt'

Please advise what I should do. Thanks a lot
Regards

**Comment by mdbarnesUCSD** [comment]
Hi @JLiandbear,

Thanks for reaching out with this issue. We will be releasing an update to resolve this in the next few days and will close this issue at that time.

**Comment by mdbarnesUCSD** [comment]
Please reach out if you experience any more issues.
