### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by JLiandbear** [AlexandrovLab/SigProfilerExtractor#187]
Hi 
I still have error with latest version of igProfilerAssignment-0.0.22. This is the error message:
Time taken to collect 100 iterations for 1 signatures is 84.26 seconds
Optimization time is 1.3349645137786865 seconds
The reconstruction error is 0.5344, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures

findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Times New Roman'] not found. Falling back to DejaVu Sans.

 De Novo Fitting .....
|████████████████████████████████████████| 82/82 [100%] in 0.5s (154.62/s) 

 Decomposing De Novo Signatures  .....
Generating plots for COSMIC_v3.3_ID_GRCh37_exome now...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 861, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 505, in spa_analyze
    final_signatures = sub.signature_decomposition(processAvg, mutation_type, layer_directory2, genome_build=genome_build,cosmic_version=cosmic_version,signature_database=signature_database, mutation_context=mutation_context, add_penalty=0.05, connected_sigs=connected_sigs,remove_penalty=0.01, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg,new_signature_thresh_hold=new_signature_thresh_hold,sig_exclusion_list=sig_exclusion_list,exome=exome, m_for_subgroups=m_for_subgroups)    
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 404, in signature_decomposition
    byte_plot = sp.run_PlotDecomposition(originalProcessAvg[denovo_cols],
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 508, in run_PlotDecomposition
    basis_plots_dict = install_cosmic_plots(context_type=mtype,
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 125, in install_cosmic_plots
    cosmic_buff_plots = sigPlt.plotID(cosmic_file_path, "buffer",
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 3950, in plotID
    data=pd.read_csv(matrix_path,sep='\t',index_col=0)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jun/envs/SigProfiler/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/jun/envs/SigProfiler/lib/python3.9/site-packages/SigProfilerAssignment/data/Reference_Signatures/GRCh37/COSMIC_v3.3_ID_GRCh37_exome.txt'****

Versions of tools:
Name: sigProfilerPlotting
Version: 1.3.8

Name: SigProfilerMatrixGenerator
Version: 1.2.13

Name: SigProfilerExtractor
Version: 1.1.16

Thanks

**Comment by mdbarnesUCSD** [comment]
Thanks @JLiandbear for the information you provided. This issue should be resolved in SigProfilerAssignment v0.0.23, which is now required in v1.1.18 of SigProfilerExtractor.
