### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by ruinw** [AlexandrovLab/SigProfilerExtractor#189]
This is the header of the seg file.
ID	chrom	loc.start	loc.end	num.mark	seg.mean
TCGA-2H-A9GF-01	1	3218610	15024591	6281	0.0615
TCGA-2H-A9GF-01	1	15027535	15500102	368	-0.3664
TCGA-2H-A9GF-01	1	15500332	21225170	3285	0.0558
TCGA-2H-A9GF-01	1	21231672	21417441	89	-0.316

when i run my code,i get this result

>>>sig.sigProfilerExtractor("seg:TCGA","CNSig","/home/data/t170306/mutation/Signature/CN/stes_tcga_pub_segments.seg",reference_genome="GRCh37",minimum_signatures=1,maximum_signatures=25,nmf_replicates=100,cpu=42)

************** Reported Current Memory Use: 0.38 GB *****************

Traceback (most recent call last):
  File "/home/data/t170306/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sample'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/data/t170306/.local/lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py", line 576, in sigProfilerExtractor
    genomes = scna.generateCNVMatrix(cnv_file_type, input_data, cnv_file_type, output)
  File "/home/data/t170306/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator/scripts/CNVMatrixGenerator.py", line 380, in generateCNVMatrix
    nmf_matrix, annotated_df = annotateSegFile(df, file_type, project, output_path)
  File "/home/data/t170306/.local/lib/python3.8/site-packages/SigProfilerMatrixGenerator/scripts/CNVMatrixGenerator.py", line 31, in annotateSegFile
    columns = list(df["sample"].unique())
  File "/home/data/t170306/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/data/t170306/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'sample'
v

**Comment by marcos-diazg** [comment]
Dear @ruinw 

Thanks for your interest! Unfortunately, this is an issue related to [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) (used in the background by SigProfilerExtractor to convert segmentation files into mutational matrices). Please feel free to reopen this issue in the appropriate repo, although you may want to try checking the required input format at https://github.com/AlexandrovLab/SigProfilerMatrixGenerator#copy-number-matrix-generation, as well as follow the example input file at https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/references/CNV/example_input/Battenberg_test.tsv.
