### ISSUE TITLE
Using mutational catalogues as input

### ISSUE THREAD

**Issue by MaryGoAround** [AlexandrovLab/SigProfilerExtractor#19]
Hi

I am using mutational catalog like this

```

Substitution	1_Sample	2_Sample	3_Sample	4_Sample
A[C>A]A	409	387	432	438
A[C>A]C	204	191	233	214
A[C>A]G	31	26	30	34

```

I typed

```
>>> os.getcwd()
'/Users/fi1d18/Downloads/test'
>>> data=os.getcwd()
>>> sig.sigProfilerExtractor("table", "example_output", data)

************** Reported Current Memory Use: 0.09 GB *****************
>>> 
```
But the process never finishes 
 can you please tell me what I am doing wring here?
Thanks a lot
[data.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4335194/data.txt)

**Comment by mishugeb** [comment]
Hi, 
Your input file name is "data.txt", but you are using "/Users/fi1d18/Downloads/test" which is not correct.  
You have to use "data.txt" as the input file name.

**Comment by MaryGoAround** [comment]
Thank you so much 

I could run but at signature 5 gave this 

```
Extracting signature 5 for mutation type 96
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sigproextractor/subroutines.py", line 428, in pnmf
    W, H, kl = nmf_fn(bootstrapGenomes,totalProcesses, init=init)  #uses custom function nnmf
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sigproextractor/subroutines.py", line 310, in nnmf
    W = model.fit_transform(genomes, W=w, H=h)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py", line 1281, in fit_transform
    W, H, n_iter_ = non_negative_factorization(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py", line 1051, in non_negative_factorization
    W, H = _initialize_nmf(X, n_components, init=init,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/decomposition/_nmf.py", line 315, in _initialize_nmf
    raise ValueError("init = '{}' can only be used when "
ValueError: init = 'nndsvdar' can only be used when n_components <= min(n_samples, n_features)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sigproextractor/sigpro.py", line 562, in sigProfilerExtractor
    processes = sub.decipher_signatures(genomes= genomes, \
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sigproextractor/subroutines.py", line 984, in decipher_signatures
    results = parallel_runs(genomes=genomes, totalProcesses=totalProcesses, iterations=totalIterations,  n_cpu=cpu, verbose = False, resample=resample, seeds = seeds, init=init, normalization_cutoff=normalization_cutoff, gpu=gpu)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sigproextractor/subroutines.py", line 461, in parallel_runs
    result_list = pool.map(pool_nmf, seeds) 
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
ValueError: init = 'nndsvdar' can only be used when n_components <= min(n_samples, n_features)
>>> 

```

**Comment by mishugeb** [comment]
Hi Again,
You cannot extract more signatures than your sample number. Please try with 4 or less than signatures. 

Thanks

**Comment by MaryGoAround** [comment]
Thank you, very helpful

Sorry all I have in output folder is `SBS96` folder inside which I see `All_solutions` folder and `All_solutions_stat.csv`

Inside the `All_solutions` I see `SBS96_1_Signatures` `SBS96_2_Signatures` `SBS96_3_Signatures` `SBS96_4_Signatures`

But I am not seeing any suggested solution, denovo like this

I worry 

Could be because of few samples or bad input?



```
THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Darwin
Nodename: loan-mac-13.local
Release: 17.7.0
Version: Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64

-------Python and Package Versions------- 
Python Version: 3.8.2
Sigproextractor Version: 0.0.5.77
SigprofilerPlotting Version: 1.1.0
SigprofilerMatrixGenerator Version: 1.1.8
Pandas version: 1.0.1
Numpy version: 1.18.1
Scipy version: 1.4.1
Scikit-learn version: 0.22.2.post1
Nimfa version: 1.4.0

-------Vital Parameters Used for the execution -------
input_type: table
inputdata: data.txt
startProcess: 1
endProcess: 10
totalIterations: 8
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default'] 
init: nndsvdar

-------Date and Time Data------- 
Date and Clock time when the execution started: 2020-03-16 16:57:18.257163

Signature extraction for SBS96 completed for 1 signatures for 0:00:07.989201! TimeStamp: 2020-03-16 16:57:26.317482

Signature extraction for SBS96 completed for 2 signatures for 0:00:06.746696! TimeStamp: 2020-03-16 16:57:33.948509

Signature extraction for SBS96 completed for 3 signatures for 0:00:07.966685! TimeStamp: 2020-03-16 16:57:43.266941
```

**Comment by mishugeb** [comment]
I can see you are using an older version. Could you please use SigProfilerExtractor? You can install that using pip install SigProfilerExtractor

**Comment by beginner984** [comment]
Thank you 

Says that

```
Last login: Mon Mar 16 20:31:26 on console
loan-mac-13:~ fi1d18$ python
Python 2.7.16 (default, Dec  3 2019, 02:03:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> pip install SigProfilerExtractor
  File "<stdin>", line 1
    pip install SigProfilerExtractor
              ^
SyntaxError: invalid syntax
>>> 

```

**Comment by mishugeb** [comment]
you need to write in that in your bash prompt. Not inside python interpreter.

**Comment by beginner984** [comment]
Thank you 

I typed 

Last login: Mon Mar 16 23:02:42 on ttys000
loan-mac-13:~ fi1d18$ pip install SigProfilerExtractor
Requirement already satisfied: SigProfilerExtractor in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.0.6)

After that I done as already but the same output 

and 

```
HIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Darwin
Nodename: loan-mac-13.local
Release: 17.7.0
Version: Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64

-------Python and Package Versions------- 
Python Version: 3.8.2
Sigproextractor Version: 0.0.5.77
SigprofilerPlotting Version: 1.1.0
SigprofilerMatrixGenerator Version: 1.1.8
Pandas version: 1.0.1
Numpy version: 1.18.1
Scipy version: 1.4.1
Scikit-learn version: 0.22.2.post1
Nimfa version: 1.4.0

-------Vital Parameters Used for the execution -------
input_type: table
inputdata: data.txt
startProcess: 1
endProcess: 3
totalIterations: 8
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default'] 
init: nndsvdar

-------Date and Time Data------- 
Date and Clock time when the execution started: 2020-03-16 23:05:27.502436

Signature extraction for SBS96 completed for 1 signatures for 0:00:08.193641! TimeStamp: 2020-03-16 23:05:35.767895

Signature extraction for SBS96 completed for 2 signatures for 0:00:07.925291! TimeStamp: 2020-03-16 23:05:44.644574

Signature extraction for SBS96 completed for 3 signatures for 0:00:13.390363! TimeStamp: 2020-03-16 23:05:59.439448

Date and Clock time when the execution ended: 2020-03-16 23:06:09.231788
-------Job Status------- 
Analysis of mutational signatures completed successfully! Total execution time: 0:00:41.729352. Results can be found in: [output] folder
```

**Comment by beginner984** [comment]
Thank you very much
Your suggestion worked and I have de novo subfolder now

But when running your example data set, I also have a folder named `DBS78` which I can not get on my own data

**Comment by mishugeb** [comment]
Hi Again,
Your own data might not have the information for DBS that's why you are not getting DBS78 results from that.

**Comment by beginner984** [comment]
Hi

I have tried hard to extract signature from my data + troubled you too much

I have pasted my whole command and my whole data here

But I am still not able to run this software correctly

I don't how to call the latest version

I have tried `pip install SigProfilerExtractor` in terminal then

`python3`
```
from sigproextractor import sigpro as sig

data = 'data.txt'

sig.sigProfilerExtractor("table", "output", data, startProcess=1, endProcess=6,totalIterations=100)
[data.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/4359509/data.txt)


```

But again job log I see this

```
THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Darwin
Nodename: loan-mac-13.local
Release: 17.7.0
Version: Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64

-------Python and Package Versions------- 
Python Version: 3.8.2
Sigproextractor Version: 0.0.5.77
SigprofilerPlotting Version: 1.1.0
SigprofilerMatrixGenerator Version: 1.1.8
Pandas version: 1.0.1
Numpy version: 1.18.1
Scipy version: 1.4.1
Scikit-learn version: 0.22.2.post1
Nimfa version: 1.4.0

-------Vital Parameters Used for the execution -------
input_type: table
inputdata: data.txt
startProcess: 1
endProcess: 6
totalIterations: 100
cpu: -1
hierarchy: False
refgen: GRCh37
genome_build: GRCh37
mtype: ['default'] 
init: nndsvdar

-------Date and Time Data------- 
Date and Clock time when the execution started: 2020-03-20 12:38:18.245211

Signature extraction for SBS96 completed for 1 signatures for 0:00:08.950784! TimeStamp: 2020-03-20 12:38:27.215385

Signature extraction for SBS96 completed for 2 signatures for 0:00:11.295454! TimeStamp: 2020-03-20 12:38:39.460469

Signature extraction for SBS96 completed for 3 signatures for 0:00:21.903583! TimeStamp: 2020-03-20 12:39:02.686488

Signature extraction for SBS96 completed for 4 signatures for 0:00:36.820637! TimeStamp: 2020-03-20 12:39:41.481418
```

I am not seeing denovo and reconstructed, I only see all solutions
