### ISSUE TITLE
New Multi-dimensional indexing error

### ISSUE THREAD

**Issue by kgeyer** [AlexandrovLab/SigProfilerExtractor#206]
Hello,

I started using the updated version of SigProfiler, and now there is an error of multi-dimensional indexing that wasn't previously present.

Let me know if you need more information from me to troubleshoot this. This is the error that I've been receiving:

```
Traceback (most recent call last):
  File "/Users/kellygeyer/Documents/gitlab/mm-nmf/code/source/sigProfiler-separate-test.py", line 41, in <module>
    main()
  File "/Users/kellygeyer/Documents/gitlab/mm-nmf/code/source/sigProfiler-separate-test.py", line 33, in main
    sig.sigProfilerExtractor("matrix", out_put, input_data,
  File "/Users/kellygeyer/miniconda3/envs/sigprof_env/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 750, in sigProfilerExtractor
    processes = sub.decipher_signatures(execution_parameters,
  File "/Users/kellygeyer/miniconda3/envs/sigprof_env/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 543, in decipher_signatures
    results = parallel_runs(execution_parameters, genomes=genomes, totalProcesses=totalProcesses, \
  File "/Users/kellygeyer/miniconda3/envs/sigprof_env/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 489, in parallel_runs
    result_list = pool.map(pool_nmf, batch_generator_pair)
  File "/Users/kellygeyer/miniconda3/envs/sigprof_env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/kellygeyer/miniconda3/envs/sigprof_env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

**Comment by kgeyer** [comment]
Thank you, I downgraded pandas and everything worked again.
