### ISSUE TITLE
When running VCFs, ValueError: Error: More than 30% of mutations were skipped.

### ISSUE THREAD

**Issue by kevlumbus** [AlexandrovLab/SigProfilerExtractor#209]
Hi I am trying to run SigProfilerExtractor in 225 tumor samples using GRCh38, which causes this error to occur:
```
Traceback (most recent call last):
  File "/home/VCF_file/pyscript_vcf.py", line 5, in <module>
  sig.sigProfilerExtractor("vcf","/home/VCF_file/","/home/VCF_file/",reference_genome = "GRCh38", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100, cpu=12)
  File "/python/Python-3.10.11_install/lib/python3.10/site-packages/SigProfilerExtractor/sigpro.py", line 542, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
  File "/python/Python-3.10.11_install/lib/python3.10/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 2700, in SigProfilerMatrixGen
eratorFunc
    raise ValueError(
ValueError: Error: More than 30% of mutations were skipped. Please check the log file for more information.
```
The errors listed on the log are mutations not recognized.
```The mutation contains bases that are not recognized. Skipping this mutation: 15 56682486 GAA G,GAAA
The mutation contains bases that are not recognized. Skipping this mutation: 15 57133624 GT G,GTT,GTTT
The mutation contains bases that are not recognized. Skipping this mutation: 15 57192374 CTT C,CT,CTTT
The mutation contains bases that are not recognized. Skipping this mutation: 15 58007797 GA G,GAA
The mutation contains bases that are not recognized. Skipping this mutation: 15 58565913 CAAA C,CAA
The mutation contains bases that are not recognized. Skipping this mutation: 15 58599750 GAA G,GA,GAAA
```
 Is there a way for me have these mutations ignored?

**Comment by marcos-diazg** [comment]
Dear @kevlumbus,

Thanks for your question. Please make sure you are using the required input files (individual somatic VCFs per sample). It seems that you have several multiallelic variants, which are very rare in somatic variant calling. Alternatively, you can directly filter out these multiallelic variants before using SigProfilerExtractor.

I hope this helps, and please let us know if you have further questions.
