### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-40: ordinal not in range(256)

### ISSUE THREAD

**Issue by anderdnavarro** [AlexandrovLab/SigProfilerExtractor#211]
Hi,

I'm trying to run SigProfilerExtractor, but I obtained the following error all the time, using my data and also the 21BRCA dataset you provide.

The output is:
```
************** Reported Current Memory Use: 0.45 GB *****************

Extracting signature 1 for mutation type 96
The matrix normalizing cutoff is 11723


process 1 continues please wait... 
execution time: 36 seconds 

Time taken to collect 1 iterations for 1 signatures is 43.6 seconds
Optimization time is 2.2899556159973145 seconds
The reconstruction error is 0.7116, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures



 De Novo Fitting .....
on 1: Exception in thread Thread-10 (run):
Traceback (most recent call last):
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
on 1:   File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
on 1:   File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/core/progress.py", line 140, in run
    alive_repr(next(spinner_player), spinner_suffix)
on 1:   File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/core/progress.py", line 165, in alive_repr
    run.last_len = print_cells(fragments, term.cols(), term, run.last_len)
on 1:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
on 1:   File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/utils/cells.py", line 109, in print_cells
    term.write(join_cells(fragment))
on 1: UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-2: ordinal not in range(256)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/SigProfilerExtractor/sigpro.py", line 860, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/SigProfilerAssignment/decomposition.py", line 424, in spa_analyze
    exposureAvg = sub.make_final_solution(processAvg, genomes, allsigids, layer_directory1, mutation_type, index, colnames, 
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 534, in make_final_solution
    with alive_bar(allgenomes.shape[1]) as bar:
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/core/progress.py", line 364, in __alive_bar
    alive_repr()
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/core/progress.py", line 165, in alive_repr
    run.last_len = print_cells(fragments, term.cols(), term, run.last_len)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/adiaz-navarro/adiaz/venv/SigProfiler/lib/python3.11/site-packages/alive_progress/utils/cells.py", line 109, in print_cells
    term.write(join_cells(fragment))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-40: ordinal not in range(256)
```

I'm using the following Conda environment:

```yml
name: SigProfiler
dependencies:
  - python=3.11.2 #I also tested python=3.9.16
  - pip=22.3.1
  - pip:
    - SigProfilerMatrixGenerator
    - SigProfilerExtractor
```

And the command I'm running is:

```python
from SigProfilerExtractor import sigpro as sig
sig.sigProfilerExtractor("matrix", #I also tested VCF option
                         "results",
                         "21BRCA/21BRCA.txt",
                         reference_genome="GRCh37",
                         minimum_signatures=1,
                         maximum_signatures=1, #I changed this to improve debugging speed
                         nmf_replicates=1, #I changed this to improve debugging speed
                         cpu=10,
                         gpu=True) #I also tried gpu=False
```

Do you know what might be happening? Let me know if you need any further information.

Thank you very much!!
Ander

**Comment by mdbarnesUCSD** [comment]
Hi @anderdnavarro,

It looks like the error is originating from the package alive-progress (I ran with alive-progress v3.1.3 without error). Could you please update your alive-progress package?

Thanks!

**Comment by anderdnavarro** [comment]
Hi @mdbarnesUCSD,

Still the same error. Here is the version of the rest of the packages, in case it is useful for you:

```
pip freeze

about-time==4.2.1
alive-progress==3.1.3
cmake==3.26.3
contourpy==1.0.7
cycler==0.11.0
filelock==3.12.0
fonttools==4.39.4
freetype-py==2.3.0
grapheme==0.6.0
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
lit==16.0.5
MarkupSafe==2.1.2
matplotlib==3.7.1
mpmath==1.3.0
networkx==3.1
nimfa==1.4.0
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==1.5.3
patsy==0.5.3
pdf2image==1.16.3
Pillow==9.5.0
psutil==5.9.5
pycairo==1.23.0
PyMuPDF==1.22.3
pyparsing==3.0.9
PyPDF2==3.0.1
python-dateutil==2.8.2
pytz==2023.3
reportlab==4.0.0
rlPyCairo==0.2.0
scikit-learn==1.2.2
scipy==1.10.1
SigProfilerAssignment==0.0.30
SigProfilerExtractor==1.1.21
SigProfilerMatrixGenerator==1.2.16
sigProfilerPlotting==1.3.13
six==1.16.0
statsmodels==0.14.0
sympy==1.12
threadpoolctl==3.1.0
torch==2.0.1
triton==2.0.0
typing_extensions==4.6.1
```

Thanks!
Ander

**Comment by mdbarnesUCSD** [comment]
Hi @anderdnavarro,

I tried to reproduce your error given the information that you provided, but have been unsuccessful in doing so. I downloaded the 21BRCA data using the [wiki documentation](https://osf.io/t6j7u/wiki/2.%20Quick%20Start%20Example/) and ran with both VCF and matrix as input on CPU using your environment package versions (except for the Nvidia packages), but these ran without error. We have end-to-end testing that is run using our CI/CD and are running without error. I am wondering if this issue is specific to your environment. If you are able to identify what is causing this issue to occur, could you please let us know?

**Comment by anderdnavarro** [comment]
Hi @mdbarnesUCSD,

Thank you very much for your efforts! I don't know what is causing the error, but I guess it is due to our Conda version is outdated.

I have created a Docker with the following Dockerfile, and SigProfiler works perfectly with the 21BRCA dataset:
```
FROM debian:bullseye
## Install linux packages and remove cache
RUN ["/bin/bash", "-c", "apt-get update && apt-get install -y apt-utils && apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev nano unzip wget zip && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*"]
## Install a specific version of Python
COPY lib/Python-3.11.3.tgz /tmp/Python-3.11.3.tgz
RUN ["/bin/bash", "-c", "cd /tmp && tar -xvf Python-3.11.3.tgz && cd Python-3.11.3 && ./configure && make && make install && cd /tmp && rm -rf Python-3.11.3 Python-3.11.3.tgz"]
## Install SigProfiler
COPY SigProfilerExtractor/ /SigProfilerExtractor
RUN ["/bin/bash", "-c", "cd /SigProfilerExtractor && pip3 install ."]
## Install reference genomes
COPY lib/install_reference_genome.py /SigProfilerExtractor/install_reference_genome.py
RUN ["/bin/bash", "-c", "cd /SigProfilerExtractor && python3 install_reference_genome.py"]
## Other pyhton modules
RUN ["/bin/bash", "-c", "pip3 install click==8.1.3"]
## Set entrypoint
COPY lib/SigProfiler.py /usr/local/bin/SigProfiler.py
ENTRYPOINT ["SigProfiler.py"]
WORKDIR /output
``` 

Thanks!
Ander

**Comment by mdbarnesUCSD** [comment]
Thanks for the update!
