### ISSUE TITLE
Decomposing De Novo Signatures

### ISSUE THREAD

**Issue by ywhnet** [AlexandrovLab/SigProfilerExtractor#247]
Hello, 
I have an error message during decomposing De Novo Signatures.
How can I handle this issue?

 Decomposing De Novo Signatures  .....
There may be an issue with the formatting of your matrix file.
There may be an issue with the formatting of your matrix file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whl/Downloads/SigProfilerExtractor/SigProfilerExtractor/sigpro.py", line 862, in sigProfilerExtractor
    decomp.spa_analyze(allgenomes, output, signatures=processAvg, genome_build=genome_build, cosmic_version=cosmic_version, exome=exome, verbose=False,
  File "/Users/whl/anaconda3/lib/python3.11/site-packages/SigProfilerAssignment/decomposition.py", line 780, in spa_analyze
    final_signatures = sub.signature_decomposition(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whl/anaconda3/lib/python3.11/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 598, in signature_decomposition
    byte_plot = sp.run_PlotDecomposition(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whl/anaconda3/lib/python3.11/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 817, in run_PlotDecomposition
    denovo_plots_dict = convert_to_imgReaderDict(denovo_plots_dict)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whl/anaconda3/lib/python3.11/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 232, in convert_to_imgReaderDict
    for name in image_dict.keys():
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mdbarnesUCSD** [comment]
Hi @ywhnet,

Please review if either of the proposed solutions in these tickets helps resolve your issue:

- https://github.com/AlexandrovLab/SigProfilerExtractor/issues/240
- https://github.com/AlexandrovLab/SigProfilerExtractor/issues/227
 Thanks!

**Comment by mdbarnesUCSD** [comment]
Please re-open if still encounter this issue after reviewing the other tickets. Thanks!
