### ISSUE TITLE
numpy version error expected np.ndarray (got numpy.ndarray)

### ISSUE THREAD

**Issue by ahgillmo** [AlexandrovLab/SigProfilerExtractor#254]
Hi, I am trying to run the Extractor on the test data set and getting a numpy error. 

The error is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniconda3/envs/MySigProfiler/lib/python3.10/site-packages/SigProfilerExtractor/sigpro.py", line 900, in sigProfilerExtractor
    ) = sub.decipher_signatures(
  File "/miniconda3/envs/MySigProfiler/lib/python3.10/site-packages/SigProfilerExtractor/subroutines.py", line 679, in decipher_signatures
    results = parallel_runs(
  File "/miniconda3/envs/MySigProfiler/lib/python3.10/site-packages/SigProfilerExtractor/subroutines.py", line 606, in parallel_runs
    result_list = pool.map(pool_nmf, batch_generator_pair)
  File "/miniconda3/envs/MySigProfiler/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/miniconda3/envs/MySigProfiler/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
    
TypeError: expected np.ndarray (got numpy.ndarray)

I have tried creating multiple environments and different version of numpy. 

I would appreciate any suggestions.

**Comment by mdbarnesUCSD** [comment]
Hi,

Could you please provide the versions of SigProfiler packages that you have installed and how you ran the code? If you are not currently, it may help to run your code from within a [`if __name__ == __main__`](https://github.com/AlexandrovLab/SigProfilerExtractor/issues/88) idiom.

**Comment by ahgillmo** [comment]
Hello.

The version numbers are:
SigProfilerMatrixGenerator is 1.2.26
SigProfilerExtractor version is 1.1.24

I am running the code on the command line in a Linux system. 
The lines of code I was testing with are:

>>> from SigProfilerExtractor import sigpro as sig
>>> sig.sigProfilerExtractor("matrix", "matrix_results", "/home/ahgillmo/Sarcoma_analysis_July2024/Sarcoma_Mutation_clusters/21BRCA/21BRCA.txt",reference_genome="GRCh38", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)


I also tried putting the commands within a script and using the if __name__ == __main__ functionality. This did not work either.

Thanks.

**Comment by mdbarnesUCSD** [comment]
Thanks, we have not made our code compatible yet with 2.0.0 release of numpy. Could you please confirm that using an earlier version (ie 1.26.4) also produces the same error?

**Comment by ahgillmo** [comment]
Hellp
