### ISSUE TITLE
Issue with PdfMerger

### ISSUE THREAD

**Issue by yingqizhang** [AlexandrovLab/SigProfilerExtractor#259]
Hi there, I have the most up-to-date SigProfilerExtractor installed (Version: 1.1.24). The python version is 3.11.3. The script I ran is `sig.sigProfilerExtractor("vcf", "results", "tumor/vcf", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)`. 

All iterations for the 10 signatures were extracted successfully. However, decomposing de novo signatures into COSMIC signatures failed. Here's the screen output:

```
 De Novo Fitting .....
|████████████████████████████████████████| 60/60 [100%] in 1.0s (65.47/s) 

 Decomposing De Novo Signatures  .....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/SigProfilerExtractor/sigpro.py", line 1116, in sigProfilerExtractor
    decomp.spa_analyze(
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/SigProfilerAssignment/decomposition.py", line 818, in spa_analyze
    final_signatures = sub.signature_decomposition(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 413, in signature_decomposition
    merger = PdfMerger()
             ^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/pypdf/_merger.py", line 42, in __init__
    deprecation_with_replacement("PdfMerger", "PdfWriter", "5.0.0")
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/pypdf/_utils.py", line 384, in deprecation_with_replacement
    deprecation(
  File "/uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/pypdf/_utils.py", line 371, in deprecation
    raise DeprecationError(msg)
pypdf.errors.DeprecationError: PdfMerger is deprecated and was removed in pypdf 5.0.0. Use PdfWriter instead.
```
Any insight on how to fix this? Thanks a lot!

**Comment by mdbarnesUCSD** [comment]
Hi @yingqizhang,

I see that you have closed this issue. Did you discover what was causing the issue? It looks like it may have been a dependency issue and hopefully updating your packages resolved the issue.

**Comment by yingqizhang** [comment]
Hi @mdbarnesUCSD! Thanks for checking in. Yes, I ended up switching out `PdfMerger()` in decompose_subroutines.py to `PdfWriter()` since the former is deprecated. And that solved the problem.

On a separate note, I am currently troubleshooting md5() (imported from Hashlib) being disabled in FIPS mode. A couple cases, I tried modifying `md5()` to `md5(usedforsecurity=False)`, and that worked out. However, in line 58 of /uufs/chpc.utah.edu/common/HIPAA/u6054863/.local/lib/python3.11/site-packages/reportlab/lib/utils.py, changing `return md5(s if isBytes(s) else s.encode('utf8')).hexdigest()` to `return md5(s if isBytes(s) else s.encode('utf8'), usedforsecurity=False).hexdigest()` didn't help. Happy to open a separate issue if needed!

**Comment by mdbarnesUCSD** [comment]
I suspect SigProfilerAssignment and SigProfilerMatrixGenerator will both need to be updated too. As of v0.1.7 of SigProfilerAssignment switched to PdfWriter and you are likely using an older version.

It may be worth starting from a clean installation with the most current versions of these packages and seeing if these resolve.
