### ISSUE TITLE
Previously reported issue with PdfMerger

### ISSUE THREAD

**Issue by syparkmd** [AlexandrovLab/SigProfilerExtractor#262]
Hi,
I'm having the same issue previously reported by [#259](https://github.com/AlexandrovLab/SigProfilerExtractor/issues/259#issue-2567449819)

```

De Novo Fitting .....
|████████████████████████████████████████| 21/21 [100%] in 0.2s (86.09/s)

 Decomposing De Novo Signatures  .....
Traceback (most recent call last):
  File "/home/users/sypark/Tools/SigProfilerExtractor/21BRCA/SPE_21brca.py", line 12, in <module>
    run()
  File "/home/users/sypark/Tools/SigProfilerExtractor/21BRCA/SPE_21brca.py", line 6, in run
    sig.sigProfilerExtractor("vcf", "results", "/home/users/sypark/Tools/SigProfilerExtractor/21BRCA/21BRCA_vcf", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerExtractor/sigpro.py", line 1116, in sigProfilerExtractor
    decomp.spa_analyze(
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 818, in spa_analyze
    final_signatures = sub.signature_decomposition(
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 413, in signature_decomposition
    merger = PdfMerger()
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/pypdf/_merger.py", line 42, in __init__
    deprecation_with_replacement("PdfMerger", "PdfWriter", "5.0.0")
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/pypdf/_utils.py", line 391, in deprecation_with_replacement
    deprecation(
  File "/home/users/sypark/miniforge3/envs/sigprofiler/lib/python3.9/site-packages/pypdf/_utils.py", line 378, in deprecation
    raise DeprecationError(msg)
pypdf.errors.DeprecationError: PdfMerger is deprecated and was removed in pypdf 5.0.0. Use PdfWriter instead.
```

I am using the versions below.
SigProfilerAssignment-0.1.8
SigProfilerExtractor-1.1.24
SigProfilerMatrixGenerator-1.2.31

**Comment by mdbarnesUCSD** [comment]
Hi @syparkmd,

Thanks for reaching out about this. We have released a patch in SigProfilerAssignment v0.1.9 that uses PdfWriter and PdfReader instead of PdfMerger to resolve this issue.
