### ISSUE TITLE
spawn issues

### ISSUE THREAD

**Issue by grigri2020** [AlexandrovLab/SigProfilerExtractor#28]
Hi,
I am using python 3.7 and run into these issues:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "anaconda3/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "anaconda3/lib/python3.7/multiprocessing/spawn.py", line 114, in _main 
    prepare(preparation_data)
  File "anaconda3/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "anaconda3/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    sig.sigProfilerExtractor("vcf", "output_may2", data, minimum_signatures=1, maximum_signatures=10)
  File "anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 521, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
  File "anaconda3/lib/python3.7/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 303, in SigProfilerMatrixGeneratorFunc
    os.remove(log_file)
FileNotFoundError: [Errno 2] No such file or directory: 'INDEL/logs/SigProfilerMatrixGenerator_INDEL_GRCh372020-05-29.out'

Am I missing something here? Thanks for you input

_Originally posted by @grigri2020 in https://github.com/AlexandrovLab/SigProfilerExtractor/issues/27#issuecomment-636047427_

**Comment by mishugeb** [comment]
Please see the following answers in the following link for the same issue: 
https://github.com/AlexandrovLab/SigProfilerExtractor/issues/27#issuecomment-625539064
