### ISSUE TITLE
UnboundLocalError: local variable 'W' referenced before assignment

### ISSUE THREAD

**Issue by ShixiangWang** [AlexandrovLab/SigProfilerExtractor#32]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 601, in pnmf
    W, H, kl = nmf_fn(bootstrapGenomes,totalProcesses, init=init, excecution_parameters=excecution_parameters)  #uses custom function nnmf
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 415, in nnmf_cpu
    net = nmf_cpu.NMF(genomes,rank=nfactors, min_iterations=min_iterations, max_iterations=max_iterations, tolerance=tolerance,test_conv=test_conv, init_method=init,seed=None)
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/nmf_cpu.py", line 78, in __init__
    self._W, self._H = self._initialise_wh(init_method)
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/nmf_cpu.py", line 127, in _initialise_wh
    W = torch.from_numpy(W).type(self._tensor_type)
UnboundLocalError: local variable 'W' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/sigpro.py", line 746, in sigProfilerExtractor
    i = i)
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 809, in decipher_signatures
    results = parallel_runs(excecution_parameters, genomes=genomes, totalProcesses=totalProcesses, verbose = False)
  File "/home/anaconda3/lib/python3.7/site-packages/SigProfilerExtractor/subroutines.py", line 731, in parallel_runs
    result_list = pool.map(pool_nmf, batch_seed_pair) 
  File "/home/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
UnboundLocalError: local variable 'W' referenced before assignment
```

**Comment by ShixiangWang** [comment]
I try reinstalling miniconda and this package and find another error when run an example:

```python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import SigProfilerExtractor
>>> from SigProfilerExtractor import sigpro as sig
>>> path_to_example_table = sig.importdata("matrix")
>>> data = path_to_example_table
>>> sig.sigProfilerExtractor("matrix", "example_output", data, opportunity_genome="GRCh38", minimum_signatures=1,            maximum_signatures=3)

************** Reported Current Memory Use: 0.18 GB *****************

Extracting signature 1 for mutation type 96
The matrix normalizig cutoff is 11723


process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 24 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
process 1 continues please wait... 
execution time: 18 seconds 

execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 19 seconds 

process 1 continues please wait... 
execution time: 26 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 28 seconds 

process 1 continues please wait... 
execution time: 19 seconds 

process 1 continues please wait... 
execution time: 15 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 15 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 16 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 18 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 17 seconds 

process 1 continues please wait... 
execution time: 22 seconds 

process 1 continues please wait... 
execution time: 13 seconds 

process 1 continues please wait... 
execution time: 12 seconds 

process 1 continues please wait... 
execution time: 12 seconds 

process 1 continues please wait... 
execution time: 10 seconds 

process 1 continues please wait... 
execution time: 9 seconds 

process 1 continues please wait... 
execution time: 7 seconds 

process 1 continues please wait... 
execution time: 7 seconds 

Time taken to collect 100 iterations for 1 signatures is 89.23 seconds
Optimization time is 4.6821348667144775 seconds
The reconstruction error is 0.7125, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures


Extracting signature 2 for mutation type 96
The matrix normalizig cutoff is 11723


process 2 continues please wait... 
execution time: 17 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 23 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 23 seconds 

process 2 continues please wait... 
execution time: 28 seconds 

process 2 continues please wait... 
execution time: 28 seconds 

process 2 continues please wait... 
execution time: 32 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 23 seconds 

process 2 continues please wait... 
execution time: 28 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 30 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 27 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 31 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 18 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 29 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 25 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 17 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 31 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 15 seconds 

process 2 continues please wait... 
execution time: 14 seconds 

process 2 continues please wait... 
execution time: 26 seconds 

process 2 continues please wait... 
execution time: 22 seconds 

process 2 continues please wait... 
execution time: 20 seconds 

process 2 continues please wait... 
execution time: 11 seconds 

process 2 continues please wait... 
execution time: 19 seconds 

process 2 continues please wait... 
execution time: 21 seconds 

process 2 continues please wait... 
execution time: 10 seconds 

process 2 continues please wait... 
execution time: 11 seconds 

Time taken to collect 100 iterations for 2 signatures is 104.89 seconds
Optimization time is 4.701096773147583 seconds
The reconstruction error is 0.059, average process stability is 1.0 and 
the minimum process stability is 1.0 for 2 signatures


Extracting signature 3 for mutation type 96
The matrix normalizig cutoff is 11723


process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 23 seconds 

process 3 continues please wait... 
execution time: 26 seconds 

process 3 continues please wait... 
execution time: 27 seconds 

process 3 continues please wait... 
execution time: 27 seconds 

process 3 continues please wait... 
execution time: 28 seconds 

process 3 continues please wait... 
execution time: 30 seconds 

process 3 continues please wait... 
execution time: 31 seconds 

process 3 continues please wait... 
execution time: 31 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 16 seconds 

process 3 continues please wait... 
execution time: 16 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 35 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 17 seconds 

process 3 continues please wait... 
execution time: 17 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 23 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 26 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 24 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 25 seconds 

process 3 continues please wait... 
execution time: 25 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 15 seconds 

process 3 continues please wait... 
execution time: 16 seconds 

process 3 continues please wait... 
execution time: 34 seconds 

process 3 continues please wait... 
execution time: 17 seconds 

process 3 continues please wait... 
execution time: 26 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 24 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 27 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 28 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 29 seconds 

process 3 continues please wait... 
execution time: 36 seconds 

process 3 continues please wait... 
execution time: 23 seconds 

process 3 continues please wait... 
execution time: 29 seconds 

process 3 continues please wait... 
execution time: 30 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 30 seconds 

process 3 continues please wait... 
execution time: 37 seconds 

process 3 continues please wait... 
execution time: 30 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 22 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 30 seconds 

process 3 continues please wait... 
execution time: 41 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 21 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

process 3 continues please wait... 
execution time: 20 seconds 

process 3 continues please wait... 
execution time: 26 seconds 

process 3 continues please wait... 
execution time: 17 seconds 

process 3 continues please wait... 
execution time: 36 seconds 

process 3 continues please wait... 
execution time: 37 seconds 

process 3 continues please wait... 
execution time: 26 seconds 

process 3 continues please wait... 
execution time: 25 seconds 

process 3 continues please wait... 
execution time: 23 seconds 

process 3 continues please wait... 
execution time: 33 seconds 

process 3 continues please wait... 
execution time: 18 seconds 

process 3 continues please wait... 
execution time: 11 seconds 

process 3 continues please wait... 
execution time: 16 seconds 

process 3 continues please wait... 
execution time: 14 seconds 

process 3 continues please wait... 
execution time: 19 seconds 

Time taken to collect 100 iterations for 3 signatures is 118.52 seconds
Optimization time is 4.95683217048645 seconds
The reconstruction error is 0.0605, average process stability is 0.99 and 
the minimum process stability is 0.97 for 3 signatures


Traceback (most recent call last):
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/lib/utils.py", line 658, in open_for_read
    return open_for_read_by_name(name,mode)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/lib/utils.py", line 602, in open_for_read_by_name
    return open(name,mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/src/Accolade_fermante.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/lib/utils.py", line 661, in open_for_read
    return getBytesIO(datareader(name) if name[:5].lower()=='data:' else urlopen(name).read())
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/src/Accolade_fermante.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py", line 953, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=add_penalty, remove_penalty=remove_penalty, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/subroutines.py", line 1356, in signature_decomposition
    sp.run_PlotDecomposition(signatures_DF, denovo_name, sigDatabases_DF, basis_names, weights, nonzero_exposures, directory+"/Decomposition_Polts", "test", mtype_par)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/PlotDecomposition.py", line 290, in run_PlotDecomposition
    gen_decomposition(denovo_name, basis_names, weights, output_path, project, mtype, reconstruction=True, statistics=statistics)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/PlotDecomposition.py", line 223, in gen_decomposition
    spd_96.gen_decomposition(denovo_name, basis_names, weights, output_path, project, reconstruction, statistics)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/PlotDecomposition_SBS96.py", line 273, in gen_decomposition
    gen_plot(denovo_name, sorted_list, output_path, project, c, reconstruction, statistics)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/PlotDecomposition_SBS96.py", line 250, in gen_plot
    draw_bracket(num_bases, c)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/PlotDecomposition_SBS96.py", line 198, in draw_bracket
    c_draw.drawImage(paths+"/src/Accolade_fermante.png", MID_WIDTH_LETTER - 15, BRACKET_SIZES[num_plts][0], width = 20, height = BRACKET_SIZES[num_plts][1], mask='auto')
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/pdfgen/canvas.py", line 953, in drawImage
    imgObj = pdfdoc.PDFImageXObject(name, image, mask=mask)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/pdfbase/pdfdoc.py", line 2089, in __init__
    src = open_for_read(source)
  File "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/reportlab/lib/utils.py", line 663, in open_for_read
    raise IOError('Cannot open resource "%s"' % name)
OSError: Cannot open resource "/home/anaconda3/envs/sigminer_sigprofiler/lib/python3.8/site-packages/SigProfilerExtractor/src/Accolade_fermante.png"
```

**Comment by ShixiangWang** [comment]
Install package from GitHub cannot fix this error.

**Comment by ShixiangWang** [comment]
Set `nmf_init = 'random'` fix the error `UnboundLocalError: local variable 'W' referenced before assignment`.

There is a bug for `nmf_init = 'alexandrov-lab-custom'`.
