### ISSUE TITLE
subroutines.py line 1410 -- shutil.rmtree OSError: [Errno 16] Device or resource busy 

### ISSUE THREAD

**Issue by mlayeghi** [AlexandrovLab/SigProfilerExtractor#43]
....
Decompositon Plot made for SBS96B

Traceback (most recent call last):

  File "/hpf/largeprojects/adam/mehdi/sp_versions/sigproex_v1.0.17/SigProfilerExtractor/sigpro.py", line 1022, in sigProfilerExtractor
    final_signatures = sub.signature_decomposition(processAvg, m, layer_directory2, genome_build=genome_build, add_penalty=add_penalty, remove_penalty=remove_penalty, mutation_context=mutation_context, make_decomposition_plots=make_decomposition_plots, originalProcessAvg=originalProcessAvg)
  File "/hpf/largeprojects/adam/mehdi/sp_versions/sigproex_v1.0.17/SigProfilerExtractor/subroutines.py", **line 1410**, in signature_decomposition
    **shutil.rmtree(directory+"/Decomposition_Plots")**
  File "/home/mlayeghi/.conda/envs/SigProfiler/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/mlayeghi/.conda/envs/SigProfiler/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/mlayeghi/.conda/envs/SigProfiler/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
**OSError: [Errno 16] Device or resource busy: '.nfs00000003906e18580003a6aa'**
EXIT STATUS 0

**Comment by mishugeb** [comment]
It looks like that is an OSError. I will try to reproduce the issue in my machine and solve that if I can successfully reproduce that.

**Comment by mlayeghi** [comment]
Thanks Mishu. If it's any help, our OS is Centos 6 & 7.

**Comment by mishugeb** [comment]
Sorry, I made a mistake in the previous comment. Please try  "make_decomposition_plots=False"

**Comment by pbiology** [comment]
This was closed, but is there a solution? I'm running into the same problem

**Comment by marcos-diazg** [comment]
Please follow the advice of the previous answer, and update the package to the latest version on GitHub by using the following commands:

```
git clone https://github.com/AlexandrovLab/SigProfilerExtractor.git
cd SigProfilerExtractor
pip install .
```

Thanks for your interest, and please let us know if you have any further issues.
