### ISSUE TITLE
SigProfilerExtractor throwing an error with my vcf files

### ISSUE THREAD

**Issue by Sonia-Bedi** [AlexandrovLab/SigProfilerExtractor#87]
Hi,

I am facing an issue with SigProfilerExtractor when I am using my vcf.
My vcf  is not working with SigProfilerExtractor. Could you help me out please.

This is the error that I am getting:

Traceback (most recent call last):
  **File "<stdin>", line 1, in <module>
  File "/Users/soniabedi/opt/anaconda3/lib/python3.8/site-packages/SigProfilerExtractor/sigpro.py", line 611, in sigProfilerExtractor
    data = datadump.SigProfilerMatrixGeneratorFunc(project_name, refgen, project, exome=exome,  bed_file=None, chrom_based=False, plot=False, gs=False)
  File "/Users/soniabedi/opt/anaconda3/lib/python3.8/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 444, in SigProfilerMatrixGeneratorFunc
    mutation_pd, skipped_mut, total, total_DINUC, mutation_dinuc_pd_all = matGen.catalogue_generator_single (lines, chrom, mutation_pd, mutation_dinuc_pd_all, mutation_types_tsb_context, vcf_path, vcf_path_original, vcf_files, bed_file_path, chrom_path, project, output_matrix, context, exome, genome, ncbi_chrom, functionFlag, bed, bed_ranges, chrom_based, plot, tsb_ref, transcript_path, tsb_stat, seqInfo, gs, log_file)
  File "/Users/soniabedi/opt/anaconda3/lib/python3.8/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py", line 359, in catalogue_generator_single
    mnv_seq += tsb_ref[chrom_string[l-1]][1]
IndexError: index out of range**

Any suggestion where am I going wrong?
Additionally, I noticed the example 21BRCA vcf files have a different format. How do I achieve that?

**Comment by mishugeb** [comment]
I have forward the issue to @mdbarnesUCSD and @ebergstr

**Comment by mdbarnesUCSD** [comment]
Please reopen this issue if you are still experiencing any problems.

**Comment by gailrosen** [comment]
I get this issue
